/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparativoRouteImport } from './routes/comparativo'
import { Route as DavidDurandRouteImport } from './routes/david-durand'
import { Route as RonaldoMartinsRouteImport } from './routes/ronaldo-martins'
import { Route as SincronizarRouteImport } from './routes/sincronizar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativoRoute = ComparativoRouteImport.update({
  id: '/comparativo',
  path: '/comparativo',
  getParentRoute: () => rootRouteImport,
} as any)
const DavidDurandRoute = DavidDurandRouteImport.update({
  id: '/david-durand',
  path: '/david-durand',
  getParentRoute: () => rootRouteImport,
} as any)
const RonaldoMartinsRoute = RonaldoMartinsRouteImport.update({
  id: '/ronaldo-martins',
  path: '/ronaldo-martins',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronizarRoute = SincronizarRouteImport.update({
  id: '/sincronizar',
  path: '/sincronizar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparativo': typeof ComparativoRoute
  '/david-durand': typeof DavidDurandRoute
  '/ronaldo-martins': typeof RonaldoMartinsRoute
  '/sincronizar': typeof SincronizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparativo': typeof ComparativoRoute
  '/david-durand': typeof DavidDurandRoute
  '/ronaldo-martins': typeof RonaldoMartinsRoute
  '/sincronizar': typeof SincronizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparativo': typeof ComparativoRoute
  '/david-durand': typeof DavidDurandRoute
  '/ronaldo-martins': typeof RonaldoMartinsRoute
  '/sincronizar': typeof SincronizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/comparativo' | '/david-durand' | '/ronaldo-martins' | '/sincronizar'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/comparativo' | '/david-durand' | '/ronaldo-martins' | '/sincronizar'
  id:
    | '__root__'
    | '/'
    | '/comparativo'
    | '/david-durand'
    | '/ronaldo-martins'
    | '/sincronizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparativoRoute: typeof ComparativoRoute
  DavidDurandRoute: typeof DavidDurandRoute
  RonaldoMartinsRoute: typeof RonaldoMartinsRoute
  SincronizarRoute: typeof SincronizarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo': {
      id: '/comparativo'
      path: '/comparativo'
      fullPath: '/comparativo'
      preLoaderRoute: typeof ComparativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/david-durand': {
      id: '/david-durand'
      path: '/david-durand'
      fullPath: '/david-durand'
      preLoaderRoute: typeof DavidDurandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ronaldo-martins': {
      id: '/ronaldo-martins'
      path: '/ronaldo-martins'
      fullPath: '/ronaldo-martins'
      preLoaderRoute: typeof RonaldoMartinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronizar': {
      id: '/sincronizar'
      path: '/sincronizar'
      fullPath: '/sincronizar'
      preLoaderRoute: typeof SincronizarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparativoRoute: ComparativoRoute,
  DavidDurandRoute: DavidDurandRoute,
  RonaldoMartinsRoute: RonaldoMartinsRoute,
  SincronizarRoute: SincronizarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
